In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [3]:
A1=np.arange(25).reshape(5,5)
B1=np.random.randn(25).reshape(5,5)
print(A1)
print(B1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[-4.82355383e-01  1.82696501e-03  2.01785546e-01 -5.46640581e-01
  -1.77458909e+00]
 [ 1.10070604e+00 -2.21049591e-01  1.11914009e+00 -1.69298386e+00
  -9.57776858e-01]
 [ 7.09931614e-01  1.57015299e+00  4.30946599e-01 -1.42949585e-01
   1.60400346e-01]
 [-3.05129970e-01  1.07256843e-01 -1.10517165e+00 -1.14982970e+00
   6.57344954e-01]
 [-8.38683198e-01  1.57764254e+00 -4.69748344e-01 -3.30162846e-01
  -2.02727340e+00]]


In [4]:
np.concatenate([A1,B1],axis=1)

array([[ 0.00000000e+00,  1.00000000e+00,  2.00000000e+00,
         3.00000000e+00,  4.00000000e+00, -4.82355383e-01,
         1.82696501e-03,  2.01785546e-01, -5.46640581e-01,
        -1.77458909e+00],
       [ 5.00000000e+00,  6.00000000e+00,  7.00000000e+00,
         8.00000000e+00,  9.00000000e+00,  1.10070604e+00,
        -2.21049591e-01,  1.11914009e+00, -1.69298386e+00,
        -9.57776858e-01],
       [ 1.00000000e+01,  1.10000000e+01,  1.20000000e+01,
         1.30000000e+01,  1.40000000e+01,  7.09931614e-01,
         1.57015299e+00,  4.30946599e-01, -1.42949585e-01,
         1.60400346e-01],
       [ 1.50000000e+01,  1.60000000e+01,  1.70000000e+01,
         1.80000000e+01,  1.90000000e+01, -3.05129970e-01,
         1.07256843e-01, -1.10517165e+00, -1.14982970e+00,
         6.57344954e-01],
       [ 2.00000000e+01,  2.10000000e+01,  2.20000000e+01,
         2.30000000e+01,  2.40000000e+01, -8.38683198e-01,
         1.57764254e+00, -4.69748344e-01, -3.30162846e-01,
        -2.

In [7]:
s1=Series([100,200,300],index=list('ABC'))
s2=Series([400,500],index=list('DE'))
print(s1)
print(s2)

A    100
B    200
C    300
dtype: int64
D    400
E    500
dtype: int64


In [8]:
pd.concat([s1,s2])

A    100
B    200
C    300
D    400
E    500
dtype: int64

In [9]:
pd.concat([s1,s2],axis=1)

0      1
A  100.0    NaN
B  200.0    NaN
C  300.0    NaN
D    NaN  400.0
E    NaN  500.0

In [10]:
df1=DataFrame(np.random.randn(12).reshape(4,3),columns=list('ABC'))
df2=DataFrame(np.random.randn(9).reshape(3,3),columns=list('ABD'))
print(df1)
print(df2)

          A         B         C
0 -0.674176  0.862655 -0.104141
1 -0.337629 -0.672394  0.813563
2  0.351504  1.581076 -0.291674
3 -1.579043  0.762681  1.012506
          A         B         D
0 -0.727457  0.455316  0.311505
1  0.966207 -0.331935 -1.136500
2  1.141235  0.482590 -0.710857


In [11]:
pd.concat([df1,df2])

A         B         C         D
0 -0.674176  0.862655 -0.104141       NaN
1 -0.337629 -0.672394  0.813563       NaN
2  0.351504  1.581076 -0.291674       NaN
3 -1.579043  0.762681  1.012506       NaN
0 -0.727457  0.455316       NaN  0.311505
1  0.966207 -0.331935       NaN -1.136500
2  1.141235  0.482590       NaN -0.710857

In [12]:
pd.concat([df1,df2],ignore_index=True)

A         B         C         D
0 -0.674176  0.862655 -0.104141       NaN
1 -0.337629 -0.672394  0.813563       NaN
2  0.351504  1.581076 -0.291674       NaN
3 -1.579043  0.762681  1.012506       NaN
4 -0.727457  0.455316       NaN  0.311505
5  0.966207 -0.331935       NaN -1.136500
6  1.141235  0.482590       NaN -0.710857

In [13]:
df1.combine_first(df2)

A         B         C         D
0 -0.674176  0.862655 -0.104141  0.311505
1 -0.337629 -0.672394  0.813563 -1.136500
2  0.351504  1.581076 -0.291674 -0.710857
3 -1.579043  0.762681  1.012506       NaN